#!/bin/sh
#
# @name 3DR Iris Quadrotor with Velodyne VLP-16
# @type Quadrotor Wide
# @class Copter
#

. ${R}etc/init.d/rc.mc_defaults

SITL_MODEL=iris_vlp16

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.1515
param set-default CA_ROTOR0_PY 0.245
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.1515
param set-default CA_ROTOR1_PY -0.1875
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.1515
param set-default CA_ROTOR2_PY -0.245
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.1515
param set-default CA_ROTOR3_PY 0.1875
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104


param set-default COM_RC_IN_MODE 1
param set-default NAV_RCL_ACT 0
param set-default COM_ARM_WO_GPS 1
param set-default COM_ARM_EKF_YAW 3.14
param set-default COM_ARM_MAG_STR 0
param set-default CBRK_IO_SAFETY 22027
param set-default CBRK_SUPPLY_CHK 894281

# Thrust & Mass Tuning for VLP-16 Payload (2.33kg total)
param set-default MPC_THR_HOVER 0.65
param set-default MPC_THR_MAX 1.0

# EKF2: Vision position, velocity, height fusion (MAG_TYPE=5 disables mag yaw preflight lock)
param set-default EKF2_EV_DELAY 0
param set-default EKF2_EV_CTRL 11
param set-default EKF2_HGT_REF 3
param set-default EKF2_GPS_CTRL 0
param set-default EKF2_BARO_CTRL 0
param set-default EKF2_MAG_TYPE 5
param set-default EKF2_EVP_NOISE 0.05
param set-default EKF2_EVV_NOISE 0.05
param set-default EKF2_EVA_NOISE 0.05

# AEQ: External heading set to use vision input
param set-default ATT_EXT_HDG_M 1

# Takeoff: Set default takeoff altitude to 1.5m and acceptance radius to 0.2m
param set-default MIS_TAKEOFF_ALT 1.5
param set-default NAV_MC_ALT_RAD 0.2

# Failsafe: Disable low battery failsafe landing (Warning only) and battery drain
param set COM_LOW_BAT_ACT 0
param set SIM_BAT_DRAIN 86400
param set BAT_LOW_THR 0
param set BAT_CRIT_THR 0
param set BAT_EMERGEN_THR 0
param set BAT_V_EMPTY 1.0
param set BAT1_V_EMPTY 1.0
