#!/bin/sh
#
# @name 3DR Iris Quadrotor with Velodyne VLP-16 (NIDAR)
#
# @type Quadrotor Wide
#

. ${R}etc/init.d/rc.mc_defaults

# Set the SITL model name explicitly so PX4 loads iris_vlp16 from sitl_gazebo-classic/models/
SITL_MODEL=iris_vlp16

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.1515
param set-default CA_ROTOR0_PY 0.245
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.1515
param set-default CA_ROTOR1_PY -0.1875
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.1515
param set-default CA_ROTOR2_PY -0.245
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.1515
param set-default CA_ROTOR3_PY 0.1875
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

param set-default LPE_FUSION 242

# EKF2: Vision position and heading, no GPS, no Mag
param set-default EKF2_EV_DELAY 5
param set-default EKF2_EV_CTRL 15
param set-default EKF2_HGT_REF 3
param set-default EKF2_GPS_CTRL 0
param set-default EKF2_MAG_TYPE 5
param set-default ATT_EXT_HDG_M 1

