#!/usr/bin/env python3
"""Render the REAL-DRONE files from nidar_config/config/hardware.yaml (+ mission_config.yaml).

    python3 catkin_ws/src/nidar_config/scripts/apply_hardware_config.py          # write
    python3 catkin_ws/src/nidar_config/scripts/apply_hardware_config.py --check  # drift only

Writes (each file carries a GENERATED header; edit hardware.yaml, never these):
    nidar_slam/config/fast_lio/nidar_hw.yaml        FAST-LIO for the Mid-360 + TFmini
    nidar_hardware/config/px4/nidar_hw.params       PX4 parameters, QGroundControl format
                                                    (Parameters -> Tools -> Load from file, or
                                                     rosrun mavros mavparam load <file>)
    nidar_hardware/config/livox/MID360_config.json  livox_ros_driver2 network config

and prints the frame chain it implies, so a wrong sign in a mount is visible before a flight.
Validation refuses combinations that cannot work (e.g. a rotated LiDAR with its own IMU).

Sim-independent: nothing here touches the Gazebo world, the vehicle SDF or the sim FAST-LIO file.
"""
import argparse
import json
import math
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.abspath(os.path.join(HERE, '..', '..'))
REPO = os.path.abspath(os.path.join(SRC, '..', '..'))
HW_CFG = os.path.join(SRC, 'nidar_config', 'config', 'hardware.yaml')
MISSION_CFG = os.path.join(SRC, 'nidar_config', 'config', 'mission_config.yaml')
OUT_FASTLIO = os.path.join(SRC, 'nidar_slam', 'config', 'fast_lio', 'nidar_hw.yaml')
OUT_PARAMS = os.path.join(SRC, 'nidar_hardware', 'config', 'px4', 'nidar_hw.params')
OUT_LIVOX = os.path.join(SRC, 'nidar_hardware', 'config', 'livox', 'MID360_config.json')

# Mid-360 internal IMU position in the LiDAR frame (Livox Mid-360 user manual; FAST-LIO's
# upstream mid360.yaml uses the inverse, the LiDAR in the IMU frame).
MID360_IMU_IN_LIDAR = (0.011, 0.02329, -0.04412)

# PX4 serial port ids (SENS_TFMINI_CFG, MAV_x_CONFIG).
PX4_PORTS = {'TELEM1': 101, 'TELEM2': 102, 'TELEM3': 103, 'TELEM4': 104, 'GPS1': 201,
             'GPS2': 202, 'GPS3': 203}
INT32, REAL32 = 6, 9

GENERATED = 'GENERATED by nidar_config/scripts/apply_hardware_config.py from hardware.yaml -- ' \
            'do not edit; edit hardware.yaml and re-run.'


class ConfigError(Exception):
    pass


def load(path, key):
    with open(path) as f:
        return yaml.safe_load(f)[key]


def rpy_matrix(roll_deg, pitch_deg, yaw_deg):
    """ROS fixed-axis RPY (R = Rz(yaw) Ry(pitch) Rx(roll)), row-major 3x3."""
    r, p, y = (math.radians(v) for v in (roll_deg, pitch_deg, yaw_deg))
    cr, sr, cp, sp, cy, sy = math.cos(r), math.sin(r), math.cos(p), math.sin(p), math.cos(y), math.sin(y)
    return [[cy * cp, cy * sp * sr - sy * cr, cy * sp * cr + sy * sr],
            [sy * cp, sy * sp * sr + cy * cr, sy * sp * cr - cy * sr],
            [-sp, cp * sr, cp * cr]]


def mat_vec(m, v):
    return [sum(m[i][k] * v[k] for k in range(3)) for i in range(3)]


def clean(v, nd=5):
    v = round(float(v), nd)
    return 0.0 if v == 0 else v


def mount_of(section, name):
    m = section.get('mount') or {}
    try:
        return {k: float(m.get(k, 0.0)) for k in ('x', 'y', 'z', 'roll', 'pitch', 'yaw')}
    except (TypeError, ValueError):
        raise ConfigError('%s.mount must be numbers {x, y, z, roll, pitch, yaw}' % name)


def derive(hw, mission):
    """Everything the generated files need, validated."""
    lidar, rng, cam, fcu, px4 = hw['lidar'], hw['rangefinder'], hw['camera'], hw['fcu'], hw['px4']
    lm = mount_of(lidar, 'lidar')
    rm = mount_of(rng, 'rangefinder')
    imu_source = str(lidar.get('imu_source', 'livox'))
    if imu_source not in ('livox', 'fcu'):
        raise ConfigError('lidar.imu_source must be livox or fcu, not %r' % imu_source)
    if imu_source == 'livox' and any(abs(lm[k]) > 1e-6 for k in ('roll', 'pitch', 'yaw')):
        raise ConfigError(
            'lidar.imu_source: livox needs the Mid-360 mounted upright and square to the body '
            '(lidar.mount roll = pitch = yaw = 0): FAST-LIO\'s world frame is that IMU\'s frame at '
            'start-up. Mount it square, or set imu_source: fcu (and time_sync: ptp).')
    if imu_source == 'fcu' and lidar.get('time_sync') != 'ptp':
        print('WARNING: imu_source fcu with time_sync %s -- LiDAR and FC IMU stamps come from '
              'different clocks; FAST-LIO needs them aligned to a few ms. Use time_sync: ptp.'
              % lidar.get('time_sync'), file=sys.stderr)
    if rm['z'] >= 0:
        raise ConfigError('rangefinder.mount.z must be NEGATIVE (the TFmini sits below base_link); '
                          'got %.3f' % rm['z'])
    if float(lidar.get('blind', 0)) <= 0:
        raise ConfigError('lidar.blind must be > 0 (propeller/frame self-returns)')
    url = str(fcu.get('url', ''))
    # Onboard UARTs wired to TELEM2 (Jetson ttyTHS*, Pi ttyAMA*/serial0); USB (ttyACM*) has no baud.
    if ':' in url and url.startswith(('/dev/ttyTHS', '/dev/ttyAMA', '/dev/serial0', '/dev/ttyS')):
        baud = int(url.rsplit(':', 1)[1])
        if baud != int(fcu.get('telem2_baud', baud)):
            raise ConfigError('fcu.url baud %d != fcu.telem2_baud %s (PX4 SER_TEL2_BAUD)'
                              % (baud, fcu.get('telem2_baud')))
    if rng.get('source') == 'fcu' and str(rng.get('px4_port', '')).upper() not in PX4_PORTS:
        raise ConfigError('rangefinder.px4_port must be one of %s' % ', '.join(sorted(PX4_PORTS)))

    R = rpy_matrix(lm['roll'], lm['pitch'], lm['yaw'])
    t_mount = [lm['x'], lm['y'], lm['z']]
    if imu_source == 'livox':
        # FAST-LIO body = Mid-360 IMU. extrinsic = LiDAR in that IMU frame (fixed by the device).
        ext_T = [-c for c in MID360_IMU_IN_LIDAR]
        ext_R = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
        imu_in_base = [a + b for a, b in zip(t_mount, mat_vec(R, MID360_IMU_IN_LIDAR))]
        imu_topic = '/nidar/livox/imu'
    else:
        # FAST-LIO body = base_link (PX4 IMU via MAVROS). extrinsic = the LiDAR mount itself.
        ext_T, ext_R, imu_in_base = t_mount, R, [0.0, 0.0, 0.0]
        imu_topic = '/mavros/imu/data'

    pad = mission['launch_pad']
    spawn_z = round(float(pad['thickness']) + float(mission['vehicle']['belly_clearance']), 4)
    return {
        'imu_source': imu_source, 'imu_topic': imu_topic,
        'lidar_mount': lm, 'rng_mount': rm, 'cam_mount': mount_of(cam, 'camera'),
        'ext_T': [clean(v) for v in ext_T],
        'ext_R': [clean(v, 6) for row in ext_R for v in row],
        'imu_in_base': [clean(v) for v in imu_in_base],
        'tfmini_offset': clean(-rm['z'], 4),
        'camera_init_world_z': spawn_z,
        'cruise_alt': float(mission['vehicle'].get('cruise_altitude_world', 1.5)),
        'yaw_rate_deg': math.degrees(float(mission['flight'].get('max_yaw_rate', 1.047))),
    }


def render_fastlio(hw, d):
    lidar, rng = hw['lidar'], hw['rangefinder']
    blind = float(lidar['blind'])
    return '''# %s
# FAST-LIO for the real drone: Livox Mid-360 (CustomMsg via livox_bridge.py) + TFmini Plus.
# Loaded by nidar_slam/launch/nidar_mapping.launch config:=...nidar_hw.yaml (hw_bringup.sh does).
common:
    lid_topic:  "/nidar/livox/lidar"   # livox_bridge.py: driver2 CustomMsg -> FAST-LIO's type
    imu_topic:  "%s"   # imu_source: %s
    time_sync_en: false                # clocks are aligned by livox_bridge.py / PTP instead
    time_offset_lidar_to_imu: 0.0

preprocess:
    lidar_type: 1                      # 1 = Livox CustomMsg (Avia/Mid-360 handler)
    scan_line: 4                       # Mid-360: 4 scan lines
    scan_rate: %d
    timestamp_unit: 3                  # unused for CustomMsg (per-point offset_time is ns)
    blind: %s                          # hardware.yaml lidar.blind: props / arms / legs

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree: 360
    det_range: %s
    # Altitude datum: published Z = TFmini range + tfmini_mount_offset - camera_init_world_z.
    # tfmini_mount_offset = -hardware.yaml rangefinder.mount.z (beam origin below base_link).
    # camera_init_world_z is the frame convention shared with the guard, FUEL's world->map TF
    # and the mission manager (mission_config.yaml launch_pad.thickness + vehicle.belly_clearance);
    # it cancels out and must stay equal to theirs, NOT be re-measured on the real vehicle.
    tfmini_mount_offset: %s
    camera_init_world_z: %s
    tfmini_range_min: %s
    tfmini_range_max: %s
    extrinsic_est_en: false
    # LiDAR pose in the IMU frame FAST-LIO integrates (%s).
    extrinsic_T: [ %s ]
    extrinsic_R: [ %s ]

publish:
    path_en:  true
    scan_publish_en:  true
    dense_publish_en: true
    scan_bodyframe_pub_en: true

pcd_save:
    pcd_save_en: false
''' % (GENERATED, d['imu_topic'], d['imu_source'], int(lidar.get('scan_rate_hz', 10)), blind,
       float(lidar.get('det_range', 40.0)), d['tfmini_offset'], d['camera_init_world_z'],
       float(rng.get('range_min', 0.1)), float(rng.get('range_max', 12.0)),
       'Mid-360 internal IMU, fixed by the device' if d['imu_source'] == 'livox'
       else 'PX4 IMU = base_link: the LiDAR mount from hardware.yaml',
       ', '.join(str(v) for v in d['ext_T']),
       ',\n                   '.join(', '.join(str(v) for v in d['ext_R'][i:i + 3]) for i in (0, 3, 6)))


def px4_params(hw, d):
    """(name, value, type, why) for the hardware .params file."""
    fcu, rng, px4 = hw['fcu'], hw['rangefinder'], hw['px4']
    rm = d['rng_mount']
    fwd = 1 if fcu.get('mavlink_forwarding', True) else 0
    p = [
        # links
        ('MAV_0_CONFIG', 101, INT32, 'TELEM1 = T12 / SiK radio to the GCS'),
        ('MAV_0_MODE', 0, INT32, 'Normal (GCS telemetry)'),
        ('SER_TEL1_BAUD', int(fcu.get('telem1_baud', 57600)), INT32, 'radio data-link baud'),
        ('MAV_0_FORWARD', fwd, INT32, 'forward GCS <-> Jetson (TAKEOFF/RTL over the radio)'),
        ('MAV_1_CONFIG', 102, INT32, 'TELEM2 = Jetson (MAVROS)'),
        ('MAV_1_MODE', 2, INT32, 'Onboard'),
        ('SER_TEL2_BAUD', int(fcu.get('telem2_baud', 921600)), INT32, 'Jetson link baud'),
        ('MAV_1_FORWARD', fwd, INT32, 'forward Jetson <-> GCS (mission STATUSTEXT, ACKs)'),
        ('UXRCE_DDS_CFG', 0, INT32, 'no ROS 2 DDS client: TELEM2 is MAVLink'),
        # estimator: FAST-LIO external vision, no GPS, no mag (same as the SITL airframe)
        ('EKF2_EV_CTRL', 11, INT32, 'vision horizontal pos + vertical pos + yaw'),
        ('EKF2_HGT_REF', 3, INT32, 'height reference = vision (FAST-LIO Z = TFmini, obstacle gated)'),
        ('EKF2_RNG_CTRL', 0, INT32, 'PX4 does not fuse the raw range (see SITL airframe notes)'),
        ('EKF2_BARO_CTRL', 1, INT32, 'baro as a backup across vision gaps'),
        ('EKF2_GPS_CTRL', 0, INT32, 'GPS-denied'),
        ('EKF2_MAG_TYPE', 5, INT32, 'no magnetometer fusion (indoors; heading from FAST-LIO)'),
        ('SYS_HAS_MAG', 0, INT32, 'no compass pre-flight checks'),
        ('COM_ARM_MAG_STR', 0, INT32, 'no field-strength check'),
        ('COM_ARM_WO_GPS', 1, INT32, 'arm without GPS'),
        ('EKF2_EV_DELAY', float(px4.get('ev_delay_ms', 60)), REAL32, 'FAST-LIO pose latency, ms'),
        ('EKF2_EVP_NOISE', 0.10, REAL32, 'measured FAST-LIO accuracy (SITL airframe notes)'),
        ('EKF2_EVA_NOISE', 0.05, REAL32, 'vision yaw noise, rad'),
        # Vision sensor = the IMU FAST-LIO integrates; Z is 0 because FAST-LIO publishes Z
        # already referred to base_link (TFmini pin).
        ('EKF2_EV_POS_X', d['imu_in_base'][0], REAL32, 'vision sensor fwd of base_link'),
        ('EKF2_EV_POS_Y', clean(-d['imu_in_base'][1]), REAL32, 'vision sensor right (FRD)'),
        ('EKF2_EV_POS_Z', 0.0, REAL32, 'Z referred to base_link by FAST-LIO already'),
        ('EKF2_RNG_POS_X', clean(rm['x']), REAL32, 'TFmini fwd of base_link'),
        ('EKF2_RNG_POS_Y', clean(-rm['y']), REAL32, 'TFmini right (FRD)'),
        ('EKF2_RNG_POS_Z', clean(-rm['z']), REAL32, 'TFmini below base_link (FRD down)'),
        ('EKF2_MIN_RNG', float(rng.get('range_min', 0.1)), REAL32, 'TFmini minimum range'),
        # flight envelope
        ('MIS_TAKEOFF_ALT', d['cruise_alt'], REAL32, 'AUTO.TAKEOFF height (mission cruise)'),
        ('MPC_THR_HOVER', float(px4.get('mpc_thr_hover', 0.45)), REAL32, 'hover throttle'),
        ('MPC_Z_VEL_MAX_UP', float(px4.get('max_climb_speed', 1.0)), REAL32, 'max climb m/s'),
        ('MPC_TKO_SPEED', float(px4.get('takeoff_speed', 0.8)), REAL32, 'takeoff climb m/s'),
        ('MPC_LAND_SPEED', float(px4.get('land_speed', 0.5)), REAL32, 'final descent m/s'),
        ('MPC_XY_VEL_MAX', float(px4.get('max_xy_speed', 1.0)), REAL32, 'horizontal cap m/s'),
        ('MC_YAWRATE_MAX', round(d['yaw_rate_deg'], 1), REAL32, 'LiDAR de-skew limit, deg/s'),
        ('MPC_YAWRAUTO_MAX', round(d['yaw_rate_deg'], 1), REAL32, 'same, auto modes'),
        # failsafes (indoor: never PX4 RTL -- a straight line home crosses the arena walls)
        ('COM_RC_IN_MODE', 0, INT32, 'RC transmitter (T12) is the safety pilot'),
        ('NAV_RCL_ACT', 3, INT32, 'RC loss -> Land'),
        ('COM_RCL_EXCEPT', 4, INT32, 'except in Offboard: the autonomous mission continues'),
        ('NAV_DLL_ACT', 0, INT32, 'GCS link loss: mission continues onboard'),
        ('COM_OF_LOSS_T', 1.0, REAL32, 'offboard setpoint timeout, s'),
        ('COM_OBL_RC_ACT', 4, INT32, 'offboard loss (Jetson stack died) -> Land'),
        ('COM_LOW_BAT_ACT', 2, INT32, 'critical battery -> Land (mission RTL fires earlier)'),
        ('CBRK_FLIGHTTERM', 0, INT32, 'terminate on attitude failure (>60 deg), as in SITL'),
    ]
    if rng.get('source') == 'fcu':
        p.append(('SENS_TFMINI_CFG', PX4_PORTS[str(rng['px4_port']).upper()], INT32,
                  'TFmini Plus on %s' % str(rng['px4_port']).upper()))
    return p


def render_params(hw, d):
    lines = ['# Onboard parameters for Vehicle 1',
             '#',
             '# %s' % GENERATED,
             '# Stack: PX4 Pro. Names and values valid on v1.14 (simulation/PX4-Autopilot-v1.14.3)',
             '# and checked against v1.16.1 (flown firmware); px4_fmu-v6x ports TELEM1/TELEM2/GPS2.',
             '# Vehicle: Multi-Rotor. Select the airframe and calibrate sensors/ESCs/RC in',
             '# QGroundControl FIRST, then load this file (it does not set geometry or tuning gains).',
             '#',
             '# Vehicle-Id Component-Id Name Value Type']
    notes = []
    for name, value, ptype, why in px4_params(hw, d):
        val = str(int(value)) if ptype == INT32 else repr(float(value))
        lines.append('1\t1\t%s\t%s\t%d' % (name, val, ptype))
        notes.append('#   %-18s %-10s %s' % (name, val, why))
    return '\n'.join(lines + ['#', '# What each value is for:'] + notes) + '\n'


def render_livox(hw):
    lidar = hw['lidar']
    host, ip = str(lidar['host_ip']), str(lidar['lidar_ip'])
    cfg = {
        'lidar_summary_info': {'lidar_type': 8},
        'MID360': {
            'lidar_net_info': {'cmd_data_port': 56100, 'push_msg_port': 56200,
                               'point_data_port': 56300, 'imu_data_port': 56400,
                               'log_data_port': 56500},
            'host_net_info': {'cmd_data_ip': host, 'cmd_data_port': 56101,
                              'push_msg_ip': host, 'push_msg_port': 56201,
                              'point_data_ip': host, 'point_data_port': 56301,
                              'imu_data_ip': host, 'imu_data_port': 56401,
                              'log_data_ip': '', 'log_data_port': 56501},
        },
        'lidar_configs': [{
            'ip': ip, 'pcl_data_type': 1, 'pattern_mode': 0,
            # Points stay in the LiDAR's own frame: the mount lives in TF/FAST-LIO, not here.
            'extrinsic_parameter': {'roll': 0.0, 'pitch': 0.0, 'yaw': 0.0, 'x': 0, 'y': 0, 'z': 0},
        }],
    }
    return json.dumps(cfg, indent=2) + '\n'


def summary(hw, d):
    lm, rm, cm = d['lidar_mount'], d['rng_mount'], d['cam_mount']
    out = ['Frame chain (base_link = FC IMU, FLU, metres / degrees):',
           '  base_link -> livox_frame  xyz (%.3f, %.3f, %.3f) rpy (%.1f, %.1f, %.1f)'
           % (lm['x'], lm['y'], lm['z'], lm['roll'], lm['pitch'], lm['yaw']),
           '  base_link -> tfmini_link  xyz (%.3f, %.3f, %.3f), beam straight down'
           % (rm['x'], rm['y'], rm['z']),
           '  base_link -> camera_link  xyz (%.3f, %.3f, %.3f) rpy (%.1f, %.1f, %.1f)'
           % (cm['x'], cm['y'], cm['z'], cm['roll'], cm['pitch'], cm['yaw']),
           '  FAST-LIO body (%s IMU) at (%.4f, %.4f, %.4f) in base_link'
           % (d['imu_source'], d['imu_in_base'][0], d['imu_in_base'][1], d['imu_in_base'][2]),
           '  FAST-LIO extrinsic_T %s' % d['ext_T'],
           '  TFmini datum: Z = range + %.4f - %.3f' % (d['tfmini_offset'], d['camera_init_world_z'])]
    return '\n'.join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--check', action='store_true', help='report drift, write nothing')
    ap.add_argument('--config', default=HW_CFG)
    ap.add_argument('--mission-config', default=MISSION_CFG)
    args = ap.parse_args(argv)
    try:
        hw = load(args.config, 'hardware')
        mission = load(args.mission_config, 'nidar')
        d = derive(hw, mission)
    except (ConfigError, KeyError) as e:
        print('hardware.yaml: %s' % e, file=sys.stderr)
        return 2
    outputs = {OUT_FASTLIO: render_fastlio(hw, d), OUT_PARAMS: render_params(hw, d),
               OUT_LIVOX: render_livox(hw)}
    drift = 0
    for path, text in outputs.items():
        rel = os.path.relpath(path, REPO)
        old = None
        if os.path.exists(path):
            with open(path) as f:
                old = f.read()
        if old == text:
            print('  unchanged  %s' % rel)
            continue
        drift += 1
        if args.check:
            print('  STALE      %s' % rel)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, 'w') as f:
                f.write(text)
            print('  wrote      %s' % rel)
    print(summary(hw, d))
    if args.check and drift:
        print('%d file(s) out of date: run apply_hardware_config.py' % drift, file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
